# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ab8b9c26c2b798fad962430206dc3ee9749b21090ddaea0db30f1ef1c202a02f1affb9bb06bb3c48617385d4fd807dc58c291d6922390ec1caf59f1e8f6c451

test:
  secret_key_base: db3fed0cbc1e631d64d0970f1c44723b565b92c7d236a696c6234f79e1a0ba61b6437505edbe52824449c2f9c119a20e57e97a92bb1df07b7bb2ceb0ba835be0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
